/*using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

public class HashConstantsWindow : EditorWindow
{
    // --- serialized list of PoolObjects
    [SerializeField]
    private List<FishStats> poolObjects = new List<FishStats>();

    private SerializedObject so;
    private SerializedProperty poolObjectsProp;

    // key used to store GUID list in EditorPrefs
    private const string k_PrefsKey = "HashConstantsWindow_GUIDs";

    [MenuItem("Tools/Generate/Hash Constants Window")]
    public static void ShowWindow()
    {
        GetWindow<HashConstantsWindow>("Hash Constants");
    }

    private void OnEnable()
    {
        so = new SerializedObject(this);
        poolObjectsProp = so.FindProperty(nameof(poolObjects));
        LoadSavedList();
    }

    private void OnDisable()
    {
        SaveList();
    }

    private void OnGUI()
    {
        so.Update();

        EditorGUILayout.LabelField("Drag PoolObject assets here:", EditorStyles.boldLabel);
        EditorGUILayout.PropertyField(poolObjectsProp, true);

        so.ApplyModifiedProperties();

        GUILayout.Space(8);
        if (GUILayout.Button("Generate HashConstants"))
            GenerateClass();
    }

    private void GenerateClass()
    {
        if (poolObjects == null || poolObjects.Count == 0)
        {
            Debug.LogWarning("[HashConstants] No PoolObjects assigned!");
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("public static class HashConstants");
        sb.AppendLine("{");
        foreach (var obj in poolObjects
                     .Where(o => o != null)
                     .OrderBy(o => o.name))
        {
            uint hash = obj.name.FNV1aHash();
            string safeName = MakeSafeIdentifier(obj.name);
            sb.AppendLine($"    public const uint {safeName} = {hash};");
        }
        sb.AppendLine("}");

        string genFolder = Path.Combine(Application.dataPath, "Scripts/Generated");
        Directory.CreateDirectory(genFolder);
        string fullPath = Path.Combine(genFolder, "HashConstants.cs");
        File.WriteAllText(fullPath, sb.ToString());

        AssetDatabase.Refresh();
        Debug.Log($"[HashConstants] Wrote {poolObjects.Count} entries to {fullPath}");
    }

    private string MakeSafeIdentifier(string raw)
    {
        var sb = new StringBuilder();
        foreach (char c in raw)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        if (sb.Length > 0 && char.IsDigit(sb[0]))
            sb.Insert(0, '_');
        return sb.ToString();
    }

    // Persist the list of GUIDs when the window closes
    private void SaveList()
    {
        var guids = poolObjects
            .Where(o => o != null)
            .Select(o =>
            {
                string path = AssetDatabase.GetAssetPath(o);
                return AssetDatabase.AssetPathToGUID(path);
            })
            .ToList();

        var wrapper = new GuidListWrapper { guids = guids };
        string json = JsonUtility.ToJson(wrapper);
        EditorPrefs.SetString(k_PrefsKey, json);
    }

    // Reload the list of assets when opening the window
    private void LoadSavedList()
    {
        poolObjects.Clear();

        if (!EditorPrefs.HasKey(k_PrefsKey))
            return;

        string json = EditorPrefs.GetString(k_PrefsKey, "");
        if (string.IsNullOrEmpty(json))
            return;

        try
        {
            var wrapper = JsonUtility.FromJson<GuidListWrapper>(json);
            foreach (var guid in wrapper.guids ?? Enumerable.Empty<string>())
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(path))
                    continue;
                var obj = AssetDatabase.LoadAssetAtPath<PoolObject>(path);
                if (obj != null)
                    poolObjects.Add(obj);
            }
        }
        catch (Exception e)
        {
            Debug.LogWarning($"[HashConstants] Failed to load saved list: {e.Message}");
        }
    }

    [Serializable]
    private class GuidListWrapper
    {
        public List<string> guids;
    }
}
*/