using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEditor.Build;
using DonutPackage.ObjectPooling;
using DonutPackage.Utils;

namespace DonutPackage.ObjectPooling.Editor
{
    public class PoolObjectHashGenerator : EditorWindow
    {
        private const string k_GenerationSymbol = "POOL_HASH_GENERATED";

        [MenuItem("DonutPackage/Generate/PoolObject Hash Enum")]
        public static void ShowWindow()
        {
            GetWindow<PoolObjectHashGenerator>("PoolObject Hash Enum");
        }

        private void OnGUI()
        {
            EditorGUILayout.LabelField("This tool automatically finds all PoolObject assets in your project and generates a hash enum from them.", EditorStyles.helpBox);
            
            GUILayout.Space(8);
            if (GUILayout.Button("Generate PoolObjectHash Enum"))
            {
                GenerateEnum();
            }
        
            if (GUILayout.Button("Force Clear Generation Symbol"))
            {
                RemoveGenerationSymbol();
            }
        }

        private void GenerateEnum()
        {
            // Find all assets of type PoolObject
            string[] guids = AssetDatabase.FindAssets("t:PoolObject");
            var allPoolObjects = new List<PoolObject>();
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                var obj = AssetDatabase.LoadAssetAtPath<PoolObject>(path);
                if (obj != null)
                {
                    allPoolObjects.Add(obj);
                }
            }

            if (allPoolObjects.Count == 0)
            {
                Debug.LogWarning("[PoolObjectHashGenerator] No PoolObject assets found in project! Clearing symbol and generating empty enum.");
                RemoveGenerationSymbol();
                GenerateEmptyEnum();
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("public enum PoolObjectHash : uint");
            sb.AppendLine("{");
            sb.AppendLine("    None = 0,");

            foreach (var obj in allPoolObjects.Distinct().OrderBy(o => o.name))
            {
                uint hash = obj.name.Hash();
                string safeName = MakeSafeIdentifier(obj.name);
                sb.AppendLine($"    {safeName} = {hash},");
            }
            sb.AppendLine("}");

            WriteEnumFile(sb.ToString());
            
            Debug.Log($"[PoolObjectHashGenerator] Wrote {allPoolObjects.Count} entries.");
        
            AddGenerationSymbol();
        }

        private void GenerateEmptyEnum()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("public enum PoolObjectHash : uint");
            sb.AppendLine("{");
            sb.AppendLine("    None = 0,");
            sb.AppendLine("}");
            WriteEnumFile(sb.ToString());
        }

        private void WriteEnumFile(string content)
        {
            string genFolder = Path.Combine(Application.dataPath, "Scripts/Generated");
            Directory.CreateDirectory(genFolder);
            string fullPath = Path.Combine(genFolder, "PoolObjectHash.cs");
            File.WriteAllText(fullPath, content);
            AssetDatabase.Refresh();
        }

        private string MakeSafeIdentifier(string raw)
        {
            if (string.IsNullOrEmpty(raw)) return "_";
            var sb = new StringBuilder();
            foreach (char c in raw) sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            if (sb.Length > 0 && char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        #region Symbol Management
        /// <summary>
        /// Gets the NamedBuildTarget for the currently selected build target group.
        /// </summary>
        private static NamedBuildTarget CurrentNamedBuildTarget
        {
            get
            {
                var buildTargetGroup = EditorUserBuildSettings.selectedBuildTargetGroup;
                return NamedBuildTarget.FromBuildTargetGroup(buildTargetGroup);
            }
        }
    
        /// <summary>
        /// Adds the generation symbol to the project's Scripting Define Symbols.
        /// </summary>
        private static void AddGenerationSymbol()
        {
            NamedBuildTarget buildTarget = CurrentNamedBuildTarget;
            string definesString = PlayerSettings.GetScriptingDefineSymbols(buildTarget);
            List<string> allDefines = definesString.Split(';').ToList();
        
            if (!allDefines.Contains(k_GenerationSymbol))
            {
                allDefines.Add(k_GenerationSymbol);
                PlayerSettings.SetScriptingDefineSymbols(buildTarget, string.Join(";", allDefines.ToArray()));
                Debug.Log($"[PoolObjectHashGenerator] Added '{k_GenerationSymbol}' to Scripting Define Symbols.");
            }
        }

        /// <summary>
        /// Removes the generation symbol from the project's Scripting Define Symbols.
        /// </summary>
        private static void RemoveGenerationSymbol()
        {
            NamedBuildTarget buildTarget = CurrentNamedBuildTarget;
            string definesString = PlayerSettings.GetScriptingDefineSymbols(buildTarget);
            List<string> allDefines = definesString.Split(';').ToList();

            if (allDefines.Contains(k_GenerationSymbol))
            {
                allDefines.Remove(k_GenerationSymbol);
                PlayerSettings.SetScriptingDefineSymbols(buildTarget, string.Join(";", allDefines.ToArray()));
                Debug.Log($"[PoolObjectHashGenerator] Removed '{k_GenerationSymbol}' from Scripting Define Symbols.");
            }
        }
        #endregion
    }
}
